(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(custom-safe-themes
   '("83e0376b5df8d6a3fbdfffb9fb0e8cf41a11799d9471293a810deb7586c131e6" "6b5c518d1c250a8ce17463b7e435e9e20faa84f3f7defba8b579d4f5925f60c1" "7661b762556018a44a29477b84757994d8386d6edee909409fabe0631952dad9" "6bdcff29f32f85a2d99f48377d6bfa362768e86189656f63adbf715ac5c1340b" "c1284dd4c650d6d74cfaf0106b8ae42270cab6c58f78efc5b7c825b6a4580417" default))
 '(elfeed-feeds
   '(("\"https://solar.lowtechmagazine.com/feeds/all.rss.xml\"" sustainability technology)
     ("https://www.thesleepingshaman.com/feed/" music)
     ("https://threatpost.com/feed/" technology security)
     ("https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml" news)
     ("https://rss.nytimes.com/services/xml/rss/nyt/US.xml" news us)
     ("https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml" news technology)
     ("https://www.theatlantic.com/feed/all/" news)
     ("https://www.currentaffairs.org/feed" news)
     ("https://bikecounterculture.com/feed" bikes)
     ("https://gravelcyclist.com/feed/" bikes)
     ("https://ridinggravel.com/feed/" bikes)
     ("https://www.adventurecycling.org/index.cfm/_api/feed/v1/default/?feedID=FD273479-62E1-BC68-648EEA8DA0714737" bikes)
     ("https://freehubmag.com/rss" bikes)
     ("http://www.nolifelikethislife.com/rss" bikes)
     ("https://www.renehersecycles.com/blog/rss" bikes)
     ("https://us11.campaign-archive.com/feed?u=260375f4049fddc623ed8499c&id=800c761067" tech)
     ("https://cycleast.com/blog/rss" bikes)
     ("https://bikesnobnyc.com/feed/" bikes)
     ("https://theradavist.com/feed" bikes)
     ("https://bikeretrogrouch.blogspot.com/rss.xml" bikes)
     ("https://www.velonews.com/rss" bikes)
     ("http://www.debian.org/News/news" linux technology debian)
     ("http://planet.debian.org/rss20.xml" linux technology debian)
     ("https://fedoramagazine.org/feed/" linux technology fedora)
     ("http://feeds.feedburner.com/ItsFoss" technology)
     ("https://lwn.net/headlines/rss" technology)
     ("http://lxer.com/module/newswire/headlines.rss" technology)
     ("http://feeds.feedburner.com/d0od?format=xml" technology linux ubuntu)
     ("https://www.aljazeera.com/xml/rss/all.xml" news)
     ("https://www.theatlantic.com/feed/best-of/" news)
     ("https://theintercept.com/feed/?lang=en" news)
     ("https://whatthefuckjusthappenedtoday.com/atom.xml" news)
     ("https://blog.cryptographyengineering.com/feed" news security)
     ("https://www.bleepingcomputer.com/feed/" news security)
     ("https://cyberlaw.stanford.edu/feeds/focus-area/privacy.rss" technology security)
     ("https://www.fireeye.com/content/fireeye-www/en_US/blog/threat-research/_jcr_content.feed" technology security)
     ("https://www.hackerone.com/blog.rss" technology security)
     ("https://www.kaspersky.com/blog/feed/" technology security)
     ("https://latesthackingnews.com/feed" technology security)
     ("https://protonmail.com/blog/feed/" technology security)
     ("https://www.schneier.com/blog/atom.xml" technology security)
     ("http://www.ehacking.net/feeds/posts/default" technology security)
     ("https://tisiphone.net/feed" technology)
     ("https://www.anandtech.com/rss/" technology)
     ("https://opensourcesecurity.io/blog/feed/" technology security)
     ("http://blogs.perl.org/atom.xml" technology perl)
     ("https://www.jeffgeerling.com/blog.xml/atom.xml" technology)
     ("https://blog.jessfraz.com/index.xml" technology)
     ("https://feeds.feedburner.com/laptopmag" technology)
     ("http://feeds.feedburner.com/Liliputing" technology)
     ("http://www.phoronix.com/rss.php" technology)
     ("http://rss.slashdot.org/Slashdot/slashdotMain" technology)
     ("https://www.effectiveperlprogramming.com/feed/" technology perl)
     ("http://thehackernews.com/feeds/posts/default" technology security)
     ("https://www.tweaktown.com/feeds/news-mf.xml" technology security)
     ("https://www.lionsroar.com/feed/" buddhism)
     ("https://jackkornfield.com/feed/" buddhism)
     ("https://tricycle.org/feed/" buddhism)
     ("http://feeds.feedburner.com/SecularBuddhism" buddhism)
     ("http://feeds.feedburner.com/theexistentialbuddhist" buddhism)
     ("https://bhikkhucintita.wordpress.com/home/blog/feed/" buddhism)))
 '(multi-vterm-dedicated-window-height 15)
 '(vterm-max-scrollback 10000))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
